README.md

📝 Added GitHub Action Badges into README.md

---

.github/workflows/node.dev.yml
.github/workflows/node.prod.yml
README.md
src/components/MusicList.vue
src/pages/Landing.vue
src/pages/Music.vue
src/pages/Music/_id.vue

1. 📱 Optimize responsive design
2. 🎨 Music link no longer jump to a new page

🎨 2020-08-27 Production Update

---

src/pages/Music/_id.vue

🐛 Fixed assets link invalid issue

---

package.json
yarn.lock

➕ Added arweave as library

---

src/api/api.js
src/api/arweave.js
src/components/Header.vue
src/store/index.js

1. ✨ Added arweave login API
2. ✨ Finished login button and dropdown menu
3. 🐛 Fixed login button became loading after sign out

✨ Added API for login, and finished the dropdown menu and login button

---

src/components/Header.vue
src/components/Layout/Space.css
src/components/Layout/Space.vue
src/pages/Landing.vue
src/pages/Music.vue
src/pages/Music/_id.vue
src/pages/Songs/Albums.vue
src/pages/Songs/Index.vue
src/pages/Songs/Singles.vue

1. 🐛 Fixed the scroll to the pages
2. 🐛 Fixed the home landing page position issue
3. 💄 Fixed the layout issue and expanded the menu

🎨 Layout fixes and position fixes, menu expanded

---

src/api/arweave.js
src/components/Header.vue
src/components/Search.vue
src/pages/Upload/Index.vue
src/pages/Upload/Single.vue
src/store/index.js

1. ✨ Finished the single music upload process
2. 💄 Changed the info of Cookie store
3. ✨ Added login requirements for pages
4. 💄 Changed the depth of the color

✨ Finished the single music upload process, Cookie storage, login requirements

---

src/api/arweave.js

✨ Added getCover API

---

src/api/arweave.js

✨ Added getMusic api

---

.github/workflows/node.dev.yml
.github/workflows/node.prod.yml

💚 Removed build section for temporary encryption action

---

src/main.js

🐛 Fixed the issue where the element-ui popup

---

src/api/arweave.js

✨ Added get single info API and reference to the others

---

src/components/User/UserInfo.vue
src/pages/User/Edit.vue
src/router/index.js

✨ Added profile edit page

---

src/components/User/UserInfo.vue

📱 Optimize responsive design

---

src/pages/Upload/Album.vue
src/pages/Upload/Podcast.vue
src/pages/Upload/Single.vue
src/pages/Upload/SoundEffect.vue

🚑 Hotfix HTML attribute issue

---

src/components/Payment.vue
src/pages/Album/_id.vue

🚑  Hotfix payment album full issue

---

src/pages/Album/_id.vue

✨ Dynamic price calculation, album purchase verification

---

src/pages/Music/_id.vue

🚑 Hotfix podcast price issue

---

src/pages/User/_id.vue
src/store/index.js

🚑 Hotfix user profile issues

---

src/pages/Podcast/Index.vue
src/pages/Songs/Albums.vue
src/pages/Songs/Index.vue
src/pages/Songs/Singles.vue
src/pages/Sound/Index.vue
src/pages/User/_id.vue

🚑 Fixed file resolution issue

---

src/api/arweave.js
src/components/Header.vue
src/store/index.js

🚑 Fixed user balance 0 or transaction error handling

---

src/pages/Upload/Album.vue
src/pages/Upload/Podcast.vue
src/pages/Upload/Single.vue
src/pages/Upload/SoundEffect.vue

🚑 Fixed CSS issue

---

src/pages/Upload/Album.vue
src/pages/Upload/Podcast.vue
src/pages/Upload/Single.vue
src/pages/Upload/SoundEffect.vue
src/store/index.js

🚑 Fixed XSS issue

---

src/pages/Album/_id.vue
src/pages/Music/_id.vue
src/pages/User/_id.vue

🚑 Preventing XSS issue

---

src/components/User/UserInfo.vue
src/pages/Album/_id.vue
src/pages/Music/_id.vue
src/pages/User/_id.vue
src/store/index.js

🚑 Fix user page loading issue and preventing XSS attack

---

src/components/Search.vue
src/components/User/UserInfo.vue

🐛 Fixed introduction display issue and search issue

---

package.json
src/components/Album/AlbumInfo.vue
src/components/Search.vue
src/pages/Album/_id.vue
src/pages/Music/_id.vue
yarn.lock

1. 🐛 Fixed search result being displayed as [object, Object]
2. 🐛 Fixed the album or music won't reload after selecting search result

🐛 Fixed search related bugs

---

src/api/arweave.js
src/components/User/UserInfo.vue
src/pages/User/Edit.vue

🐛 Fix issue #148

---

src/components/Payment.vue
src/pages/Album/_id.vue

Fixed Login prompt will happen once user click buy button

🐛 Fixed Free album should be downloadable

---

src/pages/Upload/Album.vue
src/pages/Upload/Podcast.vue
src/pages/Upload/ReviewAlbum.vue
src/pages/Upload/ReviewPodcast.vue
src/pages/Upload/ReviewSingle.vue
src/pages/Upload/ReviewSoundEffect.vue
src/pages/Upload/Single.vue
src/pages/Upload/SoundEffect.vue

✨ Added form data storage

---

src/pages/Upload/Album.vue
src/pages/Upload/Podcast.vue
src/pages/Upload/Single.vue
src/pages/Upload/SoundEffect.vue

✨ Added text limits

---

src/pages/Upload/ReviewAlbum.vue
src/pages/Upload/ReviewPodcast.vue
src/pages/Upload/ReviewSingle.vue
src/pages/Upload/ReviewSoundEffect.vue

🚑 Fix critical value missing error

---

src/pages/Album/_id.vue
src/pages/Music/_id.vue
src/store/index.js

🐛 Fixed downloading pct issue and extention issue

---

src/api/arweave.js

🐛 Fixed upload issue

---

src/api/arweave.js
src/components/User/UserInfo.vue
src/pages/Upload/Album.vue
src/pages/Upload/Index.vue
src/pages/Upload/Podcast.vue
src/pages/Upload/Single.vue
src/pages/Upload/SoundEffect.vue
src/pages/User/Edit.vue
src/store/index.js

✨ Switched to production arclight-app and fixed minor bugs

---

src/store/index.js

🐛 Fixed community get holder issue

---

README.md
src/store/index.js

- Fixed community get holder issue

🔖 Release 1.0.3

---

src/api/arweave.js
src/components/Header.vue

🐛 Fixed avatar issue
🐛 Fixed cookie expire time issue
🚑 Fix similar user error

🐛 Fixed avatar display issue, cookie exp issue and user finding issue

---

README.md
doc/zh-cn.md

📝 Added zh-cn README.md

---

src/locales/en.js

🌐 Fixed English locale missing issue

---

src/api/arweave.js
src/components/Header.vue
src/locales/en.js
src/locales/ja-jp.js
src/locales/zh-cn.js
src/locales/zh-tw.js
src/store/index.js
src/util/file.js

Signed-off-by: LemonNeko <chheese048@gmail.com>
- 修复错误的key无法处理的问题：提前检查是否是ar的key
- 修复没有余额无法登陆的问题：直接移除余额检查

🐛 add key checking, remove balance checking

---

.github/workflows/node.prerelease.deploy.yml
.github/workflows/node.release.deploy.yml

💚 Updated CI/CD scripts

---

package.json
src/App.vue
src/api/api.js
src/components/Header.vue
src/components/Song/AlbumCard.vue
src/components/Song/SingleCard.vue
src/locales/en.js
src/locales/ja-jp.js
src/locales/zh-cn.js
src/locales/zh-tw.js
src/pages/Album/_id.vue
src/pages/Music/_id.vue
src/pages/Songs/Index.vue
src/router/index.js
src/store/index.js
yarn.lock

调用的 limestone api 发生了错误
Reverts Arcucy/ArcLight#261

回滚 使 ArcLight 的价格可以显示为当前真实价值 Pull Request

---

package.json
yarn.lock

📦 Updated musicgenres-json to v1.0.2

---

src/config/blocked.json
src/pages/Music/_id.vue

Signed-off-by: LemonNeko <chheese048@gmail.com>

🐛修复无法播放的问题

---

src/api/api.js
src/components/Header.vue
src/components/KeyReader.vue
src/components/Payment.vue
src/components/uploadPriceReceipt.vue
src/pages/Upload/Album.vue
src/pages/Upload/Podcast.vue
src/pages/Upload/ReviewAlbum.vue
src/pages/Upload/ReviewPodcast.vue
src/pages/Upload/ReviewSingle.vue
src/pages/Upload/ReviewSoundEffect.vue
src/pages/Upload/Single.vue
src/pages/Upload/SoundEffect.vue
src/pages/User/Edit.vue
src/store/index.js
yarn.lock

1. ✨ 登录与 ArConnect 整合
2. ✏️ 修复 i18n 文件中的措辞问题
3. 🔥 移除不必要的 Vuex 状态依赖
4. ✨ 上传文件与个人资料页编辑适配独立的钱包文件上传界面

✨ Integrated with ArConnect
